// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220201003113_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.AddMovies", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Edit")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Edit = "Yes",
                            LentTo = "Shaun",
                            MovieName = "Wall Street",
                            Notes = "This Movie is the best.",
                            Rating = "G"
                        },
                        new
                        {
                            MovieId = 2,
                            Edit = "Yes",
                            LentTo = "Shaun",
                            MovieName = "Spriderman: No way home",
                            Notes = "This Movie is good.",
                            Rating = "PG"
                        },
                        new
                        {
                            MovieId = 3,
                            Edit = "Yes",
                            LentTo = "Shaun",
                            MovieName = "Fat Albert",
                            Notes = "This Movie is fine.",
                            Rating = "PG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
